#!/bin/bash
# entrypoint.sh - Smart startup script for transformer mining container
# Automatically detects and configures the environment for optimal operation

set -e

# ===== Globals =====
BLUE='\033[0;34m'
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
RESET='\033[0m'

# Log levels
LOG_INFO="$GREEN[INFO]$RESET"
LOG_WARN="$YELLOW[WARN]$RESET"
LOG_ERROR="$RED[ERROR]$RESET"
LOG_DEBUG="$BLUE[DEBUG]$RESET"

# Directories
SCRIPT_DIR=${SCRIPT_DIR:-"/app/mining_environment/scripts"}
CONFIG_DIR=${CONFIG_DIR:-"/app/mining_environment/config"}
LOG_DIR=${LOGS_DIR:-"/app/mining_environment/logs"}

# Các biến môi trường và đường dẫn - eBPF variables removed
# All CPU-related paths removed - GPU-only operation

# ===== ĐỊNH NGHĨA CÁC HÀM CƠ BẢN TRƯỚC =====

log() {
    local level="$1"
    local message="$2"
    echo -e "$(date '+%Y-%m-%d %H:%M:%S') ${level} ${message}"
}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# 🛡️  PRE-FLIGHT SANITY CHECKS (hostPID, memlock, perf_event_paranoid)
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
check_hostpid_and_ulimits() {
    # Generated by Copilot
    # 1) Phát hiện hostPID=false (PID namespace riêng) – eBPF tracepoint không hoạt động
    # Cải thiện kiểm tra PID namespace với nhiều phương pháp
    local hostpid_detected=false
    
    # Phương pháp 1: Kiểm tra inode của PID namespace
    local init_ns="$(stat -c %i /proc/1/ns/pid 2>/dev/null || echo '')"
    local self_ns="$(stat -c %i /proc/self/ns/pid 2>/dev/null || echo '')"
    
    # Phương pháp 2: Kiểm tra xem PID 1 có phải systemd/init không
    local pid1_comm="$(cat /proc/1/comm 2>/dev/null || echo '')"
    
    # Phương pháp 3: Kiểm tra mount namespace (container thường có mount namespace riêng)
    local host_processes="$(ps aux | grep -v docker | grep -v containerd | wc -l 2>/dev/null || echo '0')"
    
    # Xác định hostPID dựa trên multiple checks
    if [[ -n "$init_ns" && -n "$self_ns" && "$init_ns" == "$self_ns" ]]; then
        hostpid_detected=true
        log "$LOG_INFO" "✅ Phát hiện hostPID=true qua PID namespace inode check"
    elif [[ "$pid1_comm" == "systemd" || "$pid1_comm" == "init" ]]; then
        hostpid_detected=true
        log "$LOG_INFO" "✅ Phát hiện hostPID=true qua PID 1 comm check ($pid1_comm)"
    elif [[ "$host_processes" -gt 50 ]]; then
        hostpid_detected=true
        log "$LOG_INFO" "✅ Phát hiện hostPID=true qua process count check ($host_processes processes)"
    fi
    
    # Chỉ báo lỗi nếu tất cả checks đều thất bại
    if [[ "$hostpid_detected" == "false" ]]; then
        log "$LOG_WARN" "⚠️  Không thể xác nhận hostPID=true - eBPF sched_switch tracepoint có thể không hoạt động tối ưu."
        log "$LOG_WARN" "� Khuyến nghị: Chạy container với --pid=host hoặc đặt hostPID: true trong PodSpec."
        # Không exit, chỉ cảnh báo để cho phép container tiếp tục chạy
    fi

    # 2) Tự nới memlock để bpf_map_pin_to_user không thất bại
    if command -v prlimit >/dev/null 2>&1; then
        prlimit --pid $$ --memlock unlimited 2>/dev/null || \
            log "$LOG_WARN" "Không thể nới memlock – thiếu CAP_SYS_RESOURCE; hãy thêm --ulimit memlock=-1:" 
    fi

    # 3) Kiểm tra perf_event_paranoid, disable IPC-sampling nếu kernel hạn chế
    local pep="$(cat /proc/sys/kernel/perf_event_paranoid 2>/dev/null || echo '3')"
    if [[ $pep -gt 2 ]]; then
        export DISABLE_IPC_SAMPLING=1
        log "$LOG_WARN" "perf_event_paranoid=$pep (>2) – đã đặt DISABLE_IPC_SAMPLING=1 để tắt IPC sampling."
    fi
}

# ==============================================================================
# PYTHON ENVIRONMENT SETUP
# ✅ Cố định PYTHONPATH trước khi import module Python
export PYTHONPATH="/app:$PYTHONPATH"
# GPU-only operation - all CPU throttling removed

# ==============================================================================
# HÀM KHỞI TẠO EBPF - ĐÃ LOẠI BỎ
# ==============================================================================

# ===== Functions =====

setup_python_environment() {
    log "$LOG_INFO" "Thiết lập môi trường Python..."
    
    # Đảm bảo PYTHONPATH chứa /app 
    export PYTHONPATH="/app:$PYTHONPATH"
    
    # Kiểm tra các module quan trọng có import được không
    log "$LOG_DEBUG" "Kiểm tra Python path: $PYTHONPATH"
    log "$LOG_DEBUG" "Kiểm tra working directory: $(pwd)"
    
    # Test import cơ bản
    if python3 -c "import sys; sys.path.insert(0, '/app'); import app" 2>/dev/null; then
        log "$LOG_INFO" "✅ Module 'app' import thành công"
    else
        log "$LOG_WARN" "⚠️ Module 'app' không thể import, sử dụng fallback mode"
        export EBPF_MOCK_MODE=true
    fi
    
    log "$LOG_INFO" "✅ Môi trường Python đã được thiết lập"
}

 # setup_kernel_headers: removed (eBPF disabled, no kernel headers needed)
 setup_kernel_headers() {
     log "$LOG_INFO" "Bỏ qua thiết lập kernel headers (eBPF đã bị loại bỏ)"
     return 0
 }

setup_nvml_symbols() {
    log "$LOG_INFO" "Kiểm tra và thiết lập symbols cho NVML..."
    
    # Đường dẫn phổ biến cho NVML
    NVML_PATHS=(
        "/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1"
        "/usr/lib/libnvidia-ml.so.1" 
        "/usr/local/cuda/lib64/libnvidia-ml.so.1"
    )
    
    # Tìm thư viện NVML
    FOUND_NVML=""
    for path in "${NVML_PATHS[@]}"; do
        if [ -f "$path" ]; then
            FOUND_NVML=$path
            log "$LOG_INFO" "✅ Tìm thấy NVML library tại: $FOUND_NVML"
            break
        fi
    done
    
    if [ -z "$FOUND_NVML" ]; then
        log "$LOG_WARN" "⚠️ Không tìm thấy thư viện NVML ở các vị trí tiêu chuẩn"
        return 1
    fi
    
    # Luôn đảm bảo thư mục chứa NVML có trong LD_LIBRARY_PATH
    NVML_DIR="$(dirname "$FOUND_NVML")"
    OLD_LD_LIBRARY_PATH=${LD_LIBRARY_PATH:-""}
    export LD_LIBRARY_PATH="$NVML_DIR:/usr/lib/x86_64-linux-gnu:/usr/lib:/usr/local/cuda/lib64:$OLD_LD_LIBRARY_PATH"
    log "$LOG_INFO" "Đã cập nhật LD_LIBRARY_PATH (ưu tiên $NVML_DIR) để bao gồm đường dẫn NVML"

    # Tạo symlinks chỉ khi có quyền ghi, không làm fail script nếu không thể
    mkdir -p /usr/lib /usr/local/cuda/lib64 2>/dev/null || true

    # /usr/lib
    if [ ! -f "/usr/lib/libnvidia-ml.so.1" ] && [ -f "$FOUND_NVML" ]; then
        if [ -w "/usr/lib" ]; then
            log "$LOG_INFO" "Tạo symlink: /usr/lib/libnvidia-ml.so.1 -> $FOUND_NVML"
            ln -sf "$FOUND_NVML" "/usr/lib/libnvidia-ml.so.1" || \
                log "$LOG_WARN" "Không thể tạo symlink trong /usr/lib (không đủ quyền); sẽ dùng LD_LIBRARY_PATH thay thế"
        else
            log "$LOG_WARN" "Bỏ qua tạo symlink trong /usr/lib (không có quyền ghi); sẽ dùng LD_LIBRARY_PATH"
        fi
    fi

    # /usr/local/cuda/lib64
    if [ ! -f "/usr/local/cuda/lib64/libnvidia-ml.so.1" ] && [ -f "$FOUND_NVML" ]; then
        if [ -w "/usr/local/cuda/lib64" ]; then
            log "$LOG_INFO" "Tạo symlink: /usr/local/cuda/lib64/libnvidia-ml.so.1 -> $FOUND_NVML"
            ln -sf "$FOUND_NVML" "/usr/local/cuda/lib64/libnvidia-ml.so.1" || \
                log "$LOG_WARN" "Không thể tạo symlink trong /usr/local/cuda/lib64; sẽ dùng LD_LIBRARY_PATH"
        else
            log "$LOG_WARN" "Bỏ qua tạo symlink trong /usr/local/cuda/lib64 (không có quyền ghi); sẽ dùng LD_LIBRARY_PATH"
        fi
    fi

    return 0
}

setup_system() {
    log "$LOG_INFO" "Setting up system environment..."
    
    # Create needed directories
    mkdir -p "$LOG_DIR"
    mkdir -p /sys/fs/bpf || true
    mkdir -p /tmp/ebpf || true
    
    # Hardware optimization permissions setup (GPU-only)
    # CPU power management removed - GPU-only operation
    
    # Enable BPF JIT compilation for better eBPF performance
    if [ -w /proc/sys/net/core/bpf_jit_enable ]; then
        log "$LOG_INFO" "Enabling BPF JIT compiler"
        echo 1 > /proc/sys/net/core/bpf_jit_enable
    fi
    
    # Ensure eBPF subsystems are properly mounted
    if [ ! -d "/sys/fs/bpf" ] || ! mountpoint -q /sys/fs/bpf; then
        log "$LOG_INFO" "Mounting BPF filesystem"
        mount -t bpf bpffs /sys/fs/bpf || log "$LOG_WARN" "Failed to mount BPF filesystem"
    fi

    # Ensure debugfs is mounted (needed for kprobe/tracepoint attach)
    if [ ! -d "/sys/kernel/debug" ] || ! mountpoint -q /sys/kernel/debug; then
        log "$LOG_INFO" "Mounting debugfs filesystem"
        mount -t debugfs debugfs /sys/kernel/debug || log "$LOG_WARN" "Failed to mount debugfs filesystem"
    fi
    
    # Setup namespaces if enabled
    if [ "${ENABLE_NS_ISOLATION:-1}" = "1" ]; then
        log "$LOG_INFO" "Setting up namespace isolation..."
    fi
    
    # Add additional system settings for optimal performance
    log "$LOG_INFO" "Setting up performance parameters..."
    
    # Thiết lập RDT filesystem (Intel Cache Allocation Technology)
    setup_rdt_filesystem || log "$LOG_WARN" "RDT CAT không khả dụng, sẽ dùng phương pháp thay thế"
}

setup_stunnel() {
    log "$LOG_INFO" "Setting up Stunnel secure communication..."
    # Check if stunnel binary exists
    if command -v stunnel &> /dev/null; then
        log "$LOG_INFO" "Starting Stunnel service..."
        stunnel /etc/stunnel/stunnel.conf &
    else
        log "$LOG_WARN" "Stunnel not found, secure communication disabled"
    fi
}

# ------------------  Logrotate-based deletion every 1 minute ------------------
start_logrotate_daemon() {
    # **logrotate** (công cụ xoay/xoá log tầng hệ thống) chạy độc lập với ứng dụng
    if ! command -v logrotate >/dev/null 2>&1; then
        log "$LOG_WARN" "logrotate không có trong container, bỏ qua daemon xoá log"
        return 0
    fi

    mkdir -p /etc/logrotate.d /var/lib/logrotate || true

    # Tạo cấu hình logrotate cho thư mục log ứng dụng (xóa mỗi lần chạy)
    cat >/etc/logrotate.d/opus-gpu-logs <<'EOF'
/app/mining_environment/logs/*.log {
    missingok
    notifempty
    copytruncate
    rotate 0
    compress
    delaycompress
    dateext
    ifempty
    su root root
    postrotate
        # Dọn các file xoay còn sót (nếu có)
        find /app/mining_environment/logs -maxdepth 1 -type f -name '*.log.*' -delete || true
    endscript
}
EOF

    # Chạy logrotate cưỡng bức mỗi 60 giây (time-based) để đảm bảo TTL 1 phút
    nohup bash -c 'while :; do \
        logrotate -f -s /var/lib/logrotate/status /etc/logrotate.d/opus-gpu-logs >/dev/null 2>&1; \
        sleep 60; \
    done' >/dev/null 2>&1 &

    log "$LOG_INFO" "logrotate daemon started (TTL=60s) cho /app/mining_environment/logs/*.log"
}

# # setup_ebpf_environment (removed, eBPF disabled)() - REMOVED
# eBPF environment setup has been completely removed as container does not use eBPF

check_gpu_environment() {
    log "$LOG_INFO" "Checking GPU environment..."
    
    # Test NVIDIA drivers and libraries
    if [ -f /proc/driver/nvidia/version ]; then
        log "$LOG_INFO" "NVIDIA driver version: $(cat /proc/driver/nvidia/version | head -n 1)"
    else
        log "$LOG_WARN" "NVIDIA driver not detected in /proc"
    fi
    
    # Check NVML library 
    if [ -f /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1 ]; then
        log "$LOG_INFO" "NVML library detected"
    else
        log "$LOG_WARN" "NVML library not found at expected location"
    fi
    
    # Check if our GPU binaries exist
    if [ -f "$CUDA_COMMAND" ]; then
        log "$LOG_INFO" "CUDA command found at $CUDA_COMMAND"
    else
        log "$LOG_WARN" "CUDA command not found at $CUDA_COMMAND"
    fi
}

# # ensure_bpftool (removed, eBPF disabled)() - REMOVED
# bpftool installation and verification has been completely removed as container does not use eBPF

ensure_libhwloc() {
    log "$LOG_INFO" "Kiểm tra thư viện libhwloc..."
    if ldconfig -p | grep -q "libhwloc.so.15"; then
        log "$LOG_INFO" "✅ libhwloc.so.15 đã có trong hệ thống"
        return 0
    fi

    log "$LOG_WARN" "⚠️ libhwloc.so.15 chưa có, thử cài đặt..."
    apt-get update -q || true
    apt-get install -y --no-install-recommends libhwloc15 || true

    # Nếu package không tồn tại hoặc phiên bản khác, tạo symlink tới phiên bản hiện có
    if ! ldconfig -p | grep -q "libhwloc.so.15"; then
        local ALT_LIB=$(ldconfig -p | awk '/libhwloc.so/{print $4; exit}')
        if [ -n "$ALT_LIB" ] && [ -f "$ALT_LIB" ]; then
            ln -sf "$ALT_LIB" /usr/lib/x86_64-linux-gnu/libhwloc.so.15 || true
            log "$LOG_INFO" "Đã tạo symlink libhwloc.so.15 -> $ALT_LIB"
        fi
    fi

    ldconfig 2>/dev/null || true
    if ldconfig -p | grep -q "libhwloc.so.15"; then
        log "$LOG_INFO" "✅ libhwloc.so.15 sẵn sàng sau khi cài đặt/symlink"
    else
        log "$LOG_WARN" "⚠️ libhwloc.so.15 không khả dụng – không ảnh hưởng đến GPU mining"
    fi
}

setup_rdt_filesystem() {
    log "$LOG_INFO" "Thiết lập Intel RDT Cache Allocation Technology..."
    
    # Chạy script thiết lập RDT nếu tồn tại
    if [ -f "/app/setup_rdt.sh" ]; then
        chmod +x /app/setup_rdt.sh
        /app/setup_rdt.sh
        
        if [ $? -eq 0 ]; then
            log "$LOG_INFO" "✅ RDT CAT đã được thiết lập thành công"
            return 0
        else
            log "$LOG_WARN" "⚠️ Không thể thiết lập RDT CAT, plugin sẽ bị vô hiệu hóa"
            # Đã xử lý trong script setup_rdt.sh
            return 1
        fi
    else
        log "$LOG_WARN" "⚠️ Script setup_rdt.sh không tìm thấy"
        return 1
    fi
}

# # setup_bpf_filesystem (removed, eBPF disabled)() - REMOVED
# BPF filesystem setup has been completely removed as container does not use eBPF
# This includes: BPF filesystem mounting, debugfs mounting, BPF JIT compiler setup

# ===== DirectPIDRegistry Setup (replaces EventBus) =====

setup_direct_pid_registry() {
    log "$LOG_INFO" "Setting up DirectPIDRegistry (replaces EventBus)..."
    
    # DirectPIDRegistry uses in-memory process tracking with thread-safe operations
    # No external dependencies required (no RabbitMQ, Redis, or network setup)
    log "$LOG_INFO" "🧠 Using DirectPIDRegistry for process communication"
    log "$LOG_INFO" "📋 DirectPIDRegistry features:"
    log "$LOG_INFO" "   - Thread-safe process registration"
    log "$LOG_INFO" "   - Observer pattern for immediate notifications"
    log "$LOG_INFO" "   - No network dependencies"
    log "$LOG_INFO" "   - Automatic cleanup and lifecycle management"
    
    log "$LOG_INFO" "✅ DirectPIDRegistry ready (no setup required)"
}

# ===== Main =====

log "$LOG_INFO" "Starting Transformer Mining container..."
log "$LOG_INFO" "Environment: EBPF_DEBUG_MODE=${EBPF_DEBUG_MODE:-false}, EBPF_MOCK_MODE=false"

# 🚀 PRE-FLIGHT CHECKS
check_hostpid_and_ulimits

# 🚌 SETUP DIRECT PID REGISTRY (REPLACES EVENTBUS)
setup_direct_pid_registry

# ✅ BƯỚC ĐẦU TIÊN: Thiết lập môi trường Python
setup_python_environment

# Thiết lập NVML trước
setup_nvml_symbols

# THAY ĐỔI: Loại bỏ gọi hàm fix_bcc_symbol_issues
# setup_bpf_filesystem (removed, eBPF disabled)

# Đảm bảo bpftool & libhwloc sẵn sàng (khắc phục lỗi runtime)
# ensure_bpftool (removed, eBPF disabled)
ensure_libhwloc

# All CPU-related functionality has been completely removed

# Setup steps
setup_system
setup_stunnel
# setup_ebpf_environment (removed, eBPF disabled)
check_gpu_environment


# Start monitoring services in the background
log "$LOG_INFO" "Starting system monitoring..."
# GPU plugins monitoring removed - keep neutral log without referencing removed path
log "$LOG_INFO" "Monitoring: Prometheus exporter disabled"

# NVRTC fix script removed – base image đã đảm bảo thư viện NVRTC chuẩn
# Log successful initialization 
log "$LOG_INFO" "Container initialization complete. Running command: $@"

# Khởi động daemon logrotate xoá log theo thời gian (mỗi 1 phút)
start_logrotate_daemon

# Execute the provided command (usually the CMD directive from Dockerfile)
exec "$@" 