#!/usr/bin/env python3
"""
AGENTS Markdown Builder

Purpose:
- Collect and normalize Markdown files from a source directory
- Merge into a single, consistently formatted AGENTS.md
- Generate a table of contents and stable anchors

No external dependencies. Python 3.8+.

Usage:
  python tools/agents_md_builder.py build \
    --source ../.codex/rules \
    --dest ../AGENTS.md \
    --order-file ../.codex/rules/AGENTS_ORDER \
    --toc-depth 3 \
    --min-level 2

  python tools/agents_md_builder.py check --source ../.codex/rules

Ordering precedence:
  1) --order-file (plain text: one path per line; or YAML key `order:`)
  2) Front-matter `weight: <int>` (lower first)
  3) Filename numeric prefix; else lexicographic

Notes:
- Headings in source files are shifted to start at `--min-level` (default 2)
- Headings receive unique GitHub-like anchor slugs, prefixed with file slug
- Links to other .md files are rewritten to local anchors when possible
"""

from __future__ import annotations

import argparse
import dataclasses
import datetime as _dt
import os
from pathlib import Path
import re
import sys
from typing import Dict, Iterable, List, Optional, Sequence, Tuple


FILE_HEADER = """<!--
AUTO-GENERATED FILE. DO NOT EDIT.

This file is generated by tools/agents_md_builder.py
Edit sources in .codex/rules (or the configured --source), then rebuild.
-->
"""


@dataclasses.dataclass
class SourceDoc:
    path: Path
    title: str
    weight: Optional[int]
    content: str
    slug: str  # file-based slug used to prefix anchors


HEADING_RE = re.compile(r"^(?P<hashes>#{1,6})\s*(?P<title>[^#].*?)\s*$")
FENCE_RE = re.compile(r"^\s*```")
FRONT_MATTER_RE = re.compile(r"^---\s*$")
LINK_MD_RE = re.compile(r"\[(?P<text>[^\]]+)\]\((?P<url>[^)]+)\)")


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def slugify(text: str) -> str:
    text = text.strip().lower()
    # Replace spaces and separators with hyphens
    text = re.sub(r"[\s/_]+", "-", text)
    # Remove characters that are not alphanumeric or hyphens
    text = re.sub(r"[^a-z0-9\-]", "", text)
    # Collapse multiple hyphens
    text = re.sub(r"-+", "-", text)
    return text.strip('-')


def file_slug(path: Path) -> str:
    return slugify(path.stem)


def normalize_lines(text: str) -> str:
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    # Replace tabs with 4 spaces
    text = text.replace("\t", "    ")
    # Trim trailing whitespace per line
    text = "\n".join(line.rstrip() for line in text.splitlines())
    # Limit consecutive blank lines to max 2
    compact: List[str] = []
    blank_streak = 0
    for line in text.split("\n"):
        if line.strip() == "":
            blank_streak += 1
            if blank_streak <= 2:
                compact.append("")
            continue
        blank_streak = 0
        compact.append(line)
    return "\n".join(compact).strip() + "\n"


def parse_front_matter(text: str) -> Tuple[Dict[str, str], str]:
    lines = text.splitlines()
    meta: Dict[str, str] = {}
    if not lines:
        return meta, text
    if not FRONT_MATTER_RE.match(lines[0]):
        return meta, text
    # Find closing '---'
    closing = None
    for i in range(1, len(lines)):
        if FRONT_MATTER_RE.match(lines[i]):
            closing = i
            break
    if closing is None:
        return meta, text
    body_lines = lines[closing + 1 :]
    for kv in lines[1:closing]:
        if ':' in kv:
            k, v = kv.split(':', 1)
            meta[k.strip().lower()] = v.strip()
    return meta, "\n".join(body_lines)


def extract_title(text: str) -> Optional[str]:
    # Find first H1/H2 heading outside code fences
    in_fence = False
    for line in text.splitlines():
        if FENCE_RE.match(line):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        m = HEADING_RE.match(line)
        if m:
            # Return the first heading's title
            return m.group('title').strip()
    return None


def shift_headings(text: str, min_level: int, file_prefix: str, slug_counts: Dict[str, int]) -> Tuple[str, List[Tuple[int, str, str]]]:
    """
    Shift headings so that the top-most heading level becomes `min_level`.
    Also generate id anchors for each heading prefixed with file_prefix.

    Returns:
      normalized_text, list of (level, title, anchor)
    """
    lines = text.splitlines()
    # Determine smallest heading level present (outside code fences)
    smallest = None
    in_fence = False
    for line in lines:
        if FENCE_RE.match(line):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        m = HEADING_RE.match(line)
        if m:
            level = len(m.group('hashes'))
            smallest = level if smallest is None else min(smallest, level)
    if smallest is None:
        smallest = min_level
    shift = max(0, min_level - smallest)

    out: List[str] = []
    toc: List[Tuple[int, str, str]] = []
    in_fence = False
    for line in lines:
        if FENCE_RE.match(line):
            in_fence = not in_fence
            out.append(line)
            continue
        if in_fence:
            out.append(line)
            continue
        m = HEADING_RE.match(line)
        if not m:
            out.append(line)
            continue
        level = len(m.group('hashes')) + shift
        title = m.group('title').strip()
        # Create unique anchor slug (prefix with file slug)
        base = f"{file_prefix}-{slugify(title)}" if file_prefix else slugify(title)
        count = slug_counts.get(base, 0)
        slug_counts[base] = count + 1
        anchor = base if count == 0 else f"{base}-{count}"
        out.append(f"{'#' * level} {title}")
        out.append(f"<a id=\"{anchor}\"></a>")
        toc.append((level, title, anchor))
    return "\n".join(out) + "\n", toc


def rewrite_crosslinks(text: str, file_map: Dict[str, str]) -> str:
    # Convert [text](path/to/file.md#anchor) to [text](#file-slug-anchor)
    def _sub(m: re.Match) -> str:
        url = m.group('url')
        if not url.lower().endswith('.md'):
            return m.group(0)
        # Split anchor
        if '#' in url:
            path_part, anchor = url.split('#', 1)
        else:
            path_part, anchor = url, ''
        key = Path(path_part).stem.lower()
        fslug = file_map.get(key)
        if not fslug:
            return m.group(0)
        new_anchor = f"#{fslug}-{slugify(anchor)}" if anchor else f"#{fslug}"
        return f"[{m.group('text')}]({new_anchor})"

    # Only rewrite links outside fenced code blocks
    lines = text.splitlines()
    out: List[str] = []
    in_fence = False
    for line in lines:
        if FENCE_RE.match(line):
            in_fence = not in_fence
            out.append(line)
            continue
        if in_fence:
            out.append(line)
            continue
        out.append(LINK_MD_RE.sub(_sub, line))
    return "\n".join(out) + "\n"


def discover_sources(src_dir: Path, include: Sequence[str], exclude: Sequence[str]) -> List[Path]:
    all_files = list(sorted(p for p in src_dir.rglob('*.md')))
    def match_any(p: Path, patterns: Sequence[str]) -> bool:
        from fnmatch import fnmatch
        rel = str(p.relative_to(src_dir))
        return any(fnmatch(rel, pat) for pat in patterns)

    selected = [p for p in all_files if (not include or match_any(p, include)) and not match_any(p, exclude)]
    return selected


def load_order(order_file: Optional[Path]) -> Optional[List[str]]:
    if not order_file or not order_file.exists():
        return None
    text = read_text(order_file)
    # Try plain list first
    lines = [ln.strip() for ln in text.splitlines() if ln.strip() and not ln.strip().startswith('#')]
    if lines and not lines[0].startswith('order:'):
        return lines
    # Minimal YAML: expect `order:` then list items prefixed with `-`
    order: List[str] = []
    seen_order = False
    for ln in text.splitlines():
        if not seen_order:
            if ln.strip().startswith('order:'):
                seen_order = True
            continue
        if ln.strip().startswith('-'):
            item = ln.split('-', 1)[1].strip().strip('"')
            if item:
                order.append(item)
    return order if order else None


def sort_sources(paths: List[Path], order_list: Optional[List[str]]) -> List[Path]:
    if order_list:
        index = {Path(p).as_posix(): i for i, p in enumerate(order_list)}
        def key(p: Path):
            rel = p.as_posix()
            return (0, index.get(rel, 10_000), rel)
        return sorted(paths, key=key)

    def infer_weight(name: str) -> Tuple[int, str]:
        m = re.match(r"^(\d+)[-_].*", name)
        return (int(m.group(1)), name) if m else (10_000, name)

    return sorted(paths, key=lambda p: infer_weight(p.name))


def collect_documents(paths: List[Path], src_root: Path) -> List[SourceDoc]:
    docs: List[SourceDoc] = []
    for p in paths:
        raw = read_text(p)
        meta, body = parse_front_matter(raw)
        title = meta.get('title') or extract_title(body) or p.stem
        weight = None
        if 'weight' in meta:
            try:
                weight = int(str(meta['weight']).strip())
            except Exception:
                weight = None
        slug = file_slug(p)
        docs.append(SourceDoc(path=p, title=title, weight=weight, content=normalize_lines(body), slug=slug))
    # If any document has weight, sort by it
    if any(d.weight is not None for d in docs):
        docs.sort(key=lambda d: (d.weight if d.weight is not None else 10_000, d.path.as_posix()))
    return docs


def build_toc(heading_entries: List[Tuple[int, str, str]], root_level: int, depth: int) -> str:
    lines: List[str] = []
    for level, title, anchor in heading_entries:
        if level < root_level or level > root_level + depth - 1:
            continue
        indent = '  ' * (level - root_level)
        lines.append(f"{indent}- [{title}](#{anchor})")
    return "\n".join(lines) + ("\n" if lines else "")


def compile_agents(
    source_dir: Path,
    dest_file: Path,
    include: Sequence[str],
    exclude: Sequence[str],
    order_file: Optional[Path],
    toc_depth: int,
    min_level: int,
) -> Tuple[str, List[SourceDoc]]:
    paths = discover_sources(source_dir, include, exclude)
    if not paths:
        raise SystemExit(f"No markdown files found in {source_dir}")
    # Apply explicit order if provided
    paths = sort_sources(paths, load_order(order_file))
    docs = collect_documents(paths, source_dir)

    # Map for rewriting cross-file md links
    file_map = {d.path.stem.lower(): d.slug for d in docs}
    slug_counts: Dict[str, int] = {}
    merged_parts: List[str] = []
    all_headings: List[Tuple[int, str, str]] = []

    header = FILE_HEADER
    header += f"# AGENTS\n\n"
    header += f"Generated: {_dt.datetime.now().isoformat(timespec='seconds')}\n\n"
    header += "Sources (in order):\n\n"
    for d in docs:
        rel = d.path.relative_to(source_dir).as_posix()
        header += f"- {rel}\n"
    header += "\n---\n\n"
    merged_parts.append(header)

    # Normalize and assemble content
    for d in docs:
        section_header = f"## {d.title}\n\n"
        section_header += f"<small>Source: {d.path.relative_to(source_dir).as_posix()}</small>\n\n"
        merged_parts.append(section_header)

        norm = rewrite_crosslinks(d.content, file_map)
        shifted, toc_entries = shift_headings(norm, min_level=min_level, file_prefix=d.slug, slug_counts=slug_counts)
        all_headings.extend(toc_entries)
        merged_parts.append(shifted)
        merged_parts.append("\n---\n\n")

    # Build ToC based on all headings
    toc = build_toc(all_headings, root_level=min_level, depth=toc_depth)
    toc_block = "## Table of Contents\n\n" + (toc or "(No headings found)\n") + "\n---\n\n"
    merged_parts.insert(1, toc_block)

    result = "".join(merged_parts)
    write_text(dest_file, result)
    return result, docs


def check_consistency(source_dir: Path, include: Sequence[str], exclude: Sequence[str]) -> int:
    """Lightweight lints for Markdown consistency."""
    paths = discover_sources(source_dir, include, exclude)
    if not paths:
        print(f"No markdown files found in {source_dir}")
        return 1
    errors = 0
    for p in paths:
        txt = read_text(p)
        # Basic checks: heading spacing, trailing spaces, CRLF
        if '\r\n' in txt:
            print(f"[CRLF] {p}")
            errors += 1
        for i, ln in enumerate(txt.splitlines(), start=1):
            if ln.endswith('  '):
                print(f"[TRAILING SPACE] {p}:{i}")
                errors += 1
            if ln.startswith('#') and not re.match(r"^#{1,6} \S", ln):
                print(f"[HEADING SPACE] {p}:{i} -> '{ln}'")
                errors += 1
    if errors:
        print(f"Found {errors} issues. Consider normalizing via the builder output.")
    else:
        print("Markdown consistency check passed.")
    return 0 if errors == 0 else 2


def parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Compile and normalize AGENTS.md from multiple Markdown sources")
    sub = p.add_subparsers(dest='cmd', required=True)

    common = argparse.ArgumentParser(add_help=False)
    common.add_argument('--source', type=Path, default=Path('../.codex/rules'), help='Source directory containing .md files')
    common.add_argument('--include', nargs='*', default=[], help='Glob patterns to include (relative to source)')
    common.add_argument('--exclude', nargs='*', default=['**/README.md'], help='Glob patterns to exclude')

    b = sub.add_parser('build', parents=[common], help='Build AGENTS.md')
    b.add_argument('--dest', type=Path, default=Path('../AGENTS.md'), help='Destination AGENTS.md path')
    b.add_argument('--order-file', type=Path, default=None, help='Optional order file (txt or minimal yaml)')
    b.add_argument('--toc-depth', type=int, default=3, help='Depth of table of contents')
    b.add_argument('--min-level', type=int, default=2, help='Minimum heading level for merged content')

    c = sub.add_parser('check', parents=[common], help='Check markdown consistency in source dir')
    return p.parse_args(argv)


def main(argv: Optional[Sequence[str]] = None) -> int:
    ns = parse_args(argv)
    if ns.cmd == 'build':
        compile_agents(
            source_dir=ns.source,
            dest_file=ns.dest,
            include=ns.include,
            exclude=ns.exclude,
            order_file=ns.order_file,
            toc_depth=ns.toc_depth,
            min_level=ns.min_level,
        )
        print(f"Built {ns.dest} from {ns.source}")
        return 0
    elif ns.cmd == 'check':
        return check_consistency(ns.source, ns.include, ns.exclude)
    return 0


if __name__ == '__main__':
    sys.exit(main())

