FROM python:3.11-slim AS base

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY src ./src
COPY pyproject.toml README.md ./

EXPOSE 9000
CMD ["uvicorn", "appgpu.infrastructure.api.main:app", "--host", "0.0.0.0", "--port", "9000"]
